export const userData = {
    ownCommunitys: [
        {
            ID: 1,
            name: "Dota2",
            Owner: "1",
            Member: 666,
            Tag: [2, 4],
            Describe: "Best mental therapy center",
            isPrivate: true,
            coverPhoto: "https://picsum.photos/id/500/200",
        },
        {
            ID: 2,
            name: "Memeworld",
            Owner: "3",
            Member: 300,
            Tag: [3],
            Describe: "Storage of meme around the world",
            isPrivate: false,
            coverPhoto: "https://picsum.photos/id/501/200",
        },
    ],
    joinedCommunitys: [
        {
            ID: 1,
            name: "Dota2",
            Owner: "1",
            Member: 666,
            Tag: [2, 4],
            Describe: "Best mental therapy center",
            isPrivate: true,
            coverPhoto: "https://picsum.photos/id/1/200",
        },
        {
            ID: 2,
            name: "Memeworld",
            Owner: "3",
            Member: 300,
            Tag: [3],
            Describe: "Storage of meme around the world",
            isPrivate: false,
            coverPhoto: "https://picsum.photos/id/2/200",
        },
        {
            ID: 3,
            name: "IndianFood",
            Owner: "2",
            Member: 150,
            Tag: [1, 2],
            Describe: "No masara no flavor we can’t eat.",
            isPrivate: true,
            coverPhoto: "https://picsum.photos/id/3/200",
        },
        {
            ID: 4,
            name: "ThaiStreetFood",
            Owner: "3",
            Member: 50,
            Tag: [1],
            Describe: "Secret thai street food that have to try once",
            isPrivate: false,
            coverPhoto: "https://picsum.photos/id/4/200",
        },
    ],
    invitations: [
        {
            inviteID: 1,
            communityName: "Programmer community",
            memberNumber: 8000,
            coverPhoto: "https://picsum.photos/id/300/200",
            isPrivate: true,
            userName: "Passakorn puttama", //name of the person who invited
            expireDate: "28",
        },
        {
            inviteID: 2,
            communityName: "Noob community",
            memberNumber: 4000,
            coverPhoto: "https://picsum.photos/id/301/200",
            isPrivate: false,
            userName: "Kitty Melody", //name of the person who invited
            expireDate: "28",
        },
        {
            inviteID: 2,
            communityName: "Noob community",
            memberNumber: 4000,
            coverPhoto: "https://picsum.photos/id/302/200",
            isPrivate: false,
            userName: "Kitty Melody", //name of the person who invited
            expireDate: "28",
        },
    ],
}
