-- AlterTable
ALTER TABLE "Action_to_XP" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Activity_Poll" ALTER COLUMN "pollcreated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_Device" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_External_Platform" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_Report" ALTER COLUMN "reportTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_Report_Module" ALTER COLUMN "reportTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_Request" ALTER COLUMN "time" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_User_Report" ALTER COLUMN "reportedAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "start" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "end" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Analytic_View" ALTER COLUMN "time" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Announcement" ALTER COLUMN "annCreated" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "annExpired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Announcement_Approve" ALTER COLUMN "approveTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Announcement_Delete" ALTER COLUMN "deleteAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Announcement_Seen" ALTER COLUMN "seenAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Ban_Status" ALTER COLUMN "banFrom" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "banTo" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Chat_Group" ALTER COLUMN "joined" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "lefted" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Chat_Quote" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Chat_Room" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "deleted" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Community_Blacklist" ALTER COLUMN "since" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Community_User" ALTER COLUMN "joined" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Credit_Card" ALTER COLUMN "cardExpired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Detail" ALTER COLUMN "birth" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "stTime" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "endTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "File_Comment" ALTER COLUMN "commentedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "File_History" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "File_Info" ALTER COLUMN "fileExpired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Follow" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Heart_History" ALTER COLUMN "heartedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Kmutt_Point_History" ALTER COLUMN "pointTransactionAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Login_Detail" ALTER COLUMN "loginDate" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "tokenExpired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Logout_Detail" ALTER COLUMN "logoutDate" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Message" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Noti_Object" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Poll_Applicant" ALTER COLUMN "registerTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Post_Comment" ALTER COLUMN "cmTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "QR" ALTER COLUMN "expired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "lastUpdated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Question_Answer" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "lastUpdated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Question_Answer_Comment" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "lastUpdated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Question_Comment" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "lastUpdated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Question_Modvote" ALTER COLUMN "lastUpdated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Repost" ALTER COLUMN "newPostTime" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Restaurant" ALTER COLUMN "lastupdated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Restaurant_Close" ALTER COLUMN "close" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Restaurant_Open" ALTER COLUMN "open" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Restaurant_Seen_By_User" ALTER COLUMN "seenAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "expired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "SReview_Comment" ALTER COLUMN "commentedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "SReview_Restaurant_Review" ALTER COLUMN "reviewedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "SReview_Shop_Review" ALTER COLUMN "reviewedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Shop_Coupon" ALTER COLUMN "validFrom" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "validTill" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Shop_Order" ALTER COLUMN "orderPlaced" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Shop_Product_Review" ALTER COLUMN "reviewAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "ShortLink" ALTER COLUMN "expired" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "ShortLink_Delete_Link" ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Sn_Comment" ALTER COLUMN "commentedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Sn_Head" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Sn_Recent" ALTER COLUMN "viewedAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Student_Post" ALTER COLUMN "lastEdit" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "created" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "due" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Task_History" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Transaction_Detail" ALTER COLUMN "transCreated" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "User_Blocked" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "User_Report" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "Word_Report_Detail" ALTER COLUMN "reportedAt" SET DATA TYPE TIMESTAMP(0);
