export const postInfoTest = [
    {
        postId: 0,
        lang: "English",
        topic: "Hello World",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "waiting",
        pinStatus: false,
        isApprove: false,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-30",
        expiredAfterDelete: "",
        addMoreLang: [
            { lang: "Thai", topic: "สวัสดีชาวโลก", detail: "สวัสดีฉันชื่อ modlifes" },
            { lang: "Korea", topic: "unnyeong", detail: "Korean Kimchi" },
        ],
    },
    {
        postId: 1,
        lang: "English",
        topic: "Hello World1",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "waiting",
        pinStatus: false,
        isApprove: false,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-30",
        expiredAfterDelete: "",
        addMoreLang: [],
    },
    {
        postId: 2,
        lang: "English",
        topic: "Hello World2",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "waiting",
        pinStatus: false,
        isApprove: false,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-30",
        expiredAfterDelete: "",
        addMoreLang: [],
    },
    {
        postId: 3,
        lang: "English",
        topic: "Hello World3",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "approve",
        pinStatus: false,
        isApprove: true,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-13",
        expiredAfterDelete: "",
        addMoreLang: [],
    },
    {
        postId: 4,
        lang: "English",
        topic: "Hello World4",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "approve",
        pinStatus: false,
        isApprove: true,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-30",
        expiredAfterDelete: "",
        addMoreLang: [],
    },
    {
        postId: 5,
        lang: "English",
        topic: "Hello World5",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "disapprove",
        pinStatus: false,
        isApprove: false,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-12",
        expiredAfterDelete: "",
        addMoreLang: [],
    },
    {
        postId: 6,
        lang: "English",
        topic: "Hello World6",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "approve",
        pinStatus: false,
        isApprove: true,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-01",
        expiredAfterDelete: "",
        addMoreLang: [],
    },
    {
        postId: 7,
        lang: "English",
        topic: "Hello World7",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "delete",
        pinStatus: false,
        isApprove: false,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-17",
        expiredAfterDelete: "Sat Nov 14 2022 13:50:11 GMT+0700",
        addMoreLang: [],
    },
    {
        postId: 8,
        lang: "English",
        topic: "Hello World8",
        detail: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        sender: "SAMO-SIT",
        status: "delete",
        pinStatus: false,
        isApprove: false,
        targetType: "Year",
        targetValue: "1",
        postAt: new Date(),
        expiredOfPost: "2022-11-22",
        expiredAfterDelete: "Sun Nov 12 2022 02:39:11 GMT+0700",
        addMoreLang: [],
    },
]
