import { DESCRIPTION } from "./descTest"

export const OBJECTS = [
    {
        id: 0,
        avatarImg: "https://s.isanook.com/jo/0/ud/488/2441749/roseblackpink.jpg",
        userName: "User1234",
        description: DESCRIPTION[0].template,
        isRead: true,
        date: new Date("November 11, 2022 14:30:00"),
        module: "Chat",
    },
    {
        id: 1,
        avatarImg: "https://media.wired.com/photos/5cdefb92b86e041493d389df/2:1/w_1500,h_750,c_limit/Culture-Grumpy-Cat-487386121.jpg",
        userName: "Userrrrr",
        description: "sdasdf sadf asfasf",
        isRead: false,
        date: new Date("November 11, 2022 09:38:00"),
        module: "Shop",
    },
    {
        id: 2,
        avatarImg: "https://assets.puzzlefactory.pl/puzzle/235/573/original.jpg",
        userName: "treafd",
        description: DESCRIPTION[1].template,
        isRead: false,
        date: new Date("November 9, 2022 09:38:00"),
        module: "Shop",
    },
    {
        id: 3,
        avatarImg: "https://assets.puzzlefactory.pl/puzzle/235/573/original.jpg",
        userName: "fghghjf",
        description: DESCRIPTION[1].template,
        isRead: false,
        date: new Date("March 18, 2022 09:38:00"),
        module: "Chat",
    },
    {
        id: 4,
        avatarImg: "https://assets.puzzlefactory.pl/puzzle/235/573/original.jpg",
        userName: "benhan",
        description: DESCRIPTION[1].template,
        isRead: false,
        date: new Date("October 19, 2020 09:38:00"),
        module: "Chat",
    },
    {
        id: 5,
        avatarImg: "https://assets.puzzlefactory.pl/puzzle/235/573/original.jpg",
        userName: "benhan",
        description: DESCRIPTION[1].template,
        isRead: false,
        date: new Date("October 19, 2020 09:38:00"),
        module: "Chat",
    },
    {
        id: 6,
        avatarImg: "https://assets.puzzlefactory.pl/puzzle/235/573/original.jpg",
        userName: "benhan",
        description: DESCRIPTION[1].template,
        isRead: false,
        date: new Date("November 1, 2022 09:38:00"),
        module: "Chat",
    },
]
