export let QUESTIONS = [
    {
        qId: "aB23C21kc",
        qCreator: "",
        q_created: "2023-02-17T10:20:30.451Z",
        q_anonymousFlag: false,
        q_lastUpdated: "2023-02-17T10:20:30.451Z",
        qTitle: "Why should pi be considered as transcendental number?",
        qDesc: "This is from my number theory class. Could anyone elaborate more about not just only pi, but for all transcendental numbers as whole?",
        voteCount: 150,
        selectedTags: [],
        q_fileName: "",
        q_fileLink: "",
        answers: [],
        q_comments: [
            {
                q_commentId: 1,
                qMentCommentor: "",
                q_ment_anonymousFlag: true,
                q_ment_created: "2023-02-17T10:45:30.451Z",
                q_ment_lastUpdated: "2023-02-17T10:45:30.451Z",
                q_comment: "What do you want to know specifically? There're tons of topics in transcendental number!",
                q_ment_positiveFlag: false,
                q_ment_negativeFlag: false,
            },
        ],
    },

    {
        qId: "adsamD3kc",
        qCreator: "",
        q_anonymousFlag: true,
        q_created: "2023-02-12T10:20:30.234Z",
        q_lastUpdated: "2023-02-13T02:20:30.699Z",
        qTitle: "Why derivative of absolute function is undefined at x equals 0?",
        qDesc: "Derivative in this case is the first derivative",
        voteCount: -42,
        selectedTags: [],
        q_fileName: "",
        q_fileLink: "",
        answers: [],
        q_comments: [],
    },

    {
        qId: "asXS2312M",
        qCreator: "dasnd231MdksmSDMk",
        q_ment_anonymousFlag: false,
        q_created: "",
        q_lastUpdated: "",
        qTitle: "Just broken up with my dearest love",
        qDesc: "How should I cope with this? Will I ever find such a campus beauty like her?",
        voteCount: 12,
        selectedTags: [{ tagId: 13 }, { tagId: 17 }],
        q_fileName: "heart-shaped-bear.jpg",
        q_fileLink: "https://studentlife.me/storage/heart-shaped-bear.jpg",
        answers: [
            {
                answerId: "",
                ansCreator: "",
                ans_anonymousFlag: false,
                ans_created: "",
                ans_lastUpdated: "",
                answerDesc: "",
                ans_fileName: "",
                ans_fileLink: "",
                ans_comments: [
                    {
                        ans_commentId: 1,
                        ansMentCommentor: "",
                        ans_ment_anonymousFlag: false,
                        ans_ment_created: "",
                        ans_ment_lastUpdated: "",
                        ans_comment: "",
                    },
                ],
            },
        ],
        q_comments: [
            {
                q_commentId: 1,
                qMentCommentor: "",
                q_ment_anonymousFlag: true,
                q_ment_created: "",
                q_ment_lastUpdated: "",
                q_comment: "I'm sure that times will comes for everyone, so please be patient and have faith in it ;D",
                q_ment_positiveFlag: true,
                q_ment_negativeFlag: false,
            },
        ],
    },
]
