export const FRIEND = [
    {
        UserId: "1",
        Fname: "Jennie",
        Lname: "Kim",
        Gender: "F",
        Age: "26",
        Faculty: "Faculty Of Enginneering",
        url: "https://lh3.googleusercontent.com/Km2FSe-U_oW1ZT1LK1u-p0nsH_QTucR7l_sUU2UvlgZpAjQaj2Oik4te9iFUVmqthLCd-6VLPtoDL9iAcs7mL7tcpSOd0tCMAtPUISBFtjMh0WI=w1600-rj-l80-nu-e365",
        interestId: [4, 1, 6, 7, 9],
        rate: 9,
    },
    {
        UserId: "2",
        Fname: "Kim",
        Lname: "Jisoo",
        Gender: "F",
        Age: "27",
        Faculty: "Doctor of Philosophy Program in industrial and Manufacturing System Engineering",
        url: "https://lh3.googleusercontent.com/MDVfO5G8cmGAKLcNXXdik1iTJe92ZcNoHbPTB4lbn0KutHvtWcBXyFEApa9x20HHg0NCrVQfxuU5u3mIsFYhM71aPJJ5XrXfOZOBRJFSYfAAM1U=w1600-rj-l80-nu-e365",
        interestId: [76, 23],
        rate: 7,
    },
    {
        UserId: "3",
        Fname: "Lalisa",
        Lname: "Manoban",
        Gender: "F",
        Age: "25",
        Faculty: "Department of Control System and Instrumentation Engineering",
        url: "https://lh3.googleusercontent.com/FQ0PlEhb6lDNLSAYiZEb_80MYlzn-ev3pEGJXC8TvBQlTcKdxAPsp3Lsnn9EZod88FHSMu6GFn2QAKnRsaRg-OBt-m_zNYow6M85Jrw1RC8FGzAD=w1600-rj-l80-nu-e365",
        interestId: [12, 36, 13, 53, 11],
        rate: 7,
    },
    {
        UserId: "4",
        Fname: "Park",
        Lname: "Chaeyoung",
        Gender: "F",
        Age: "25",
        Faculty: "Department of Electronic and Telecommunication Engineering",
        url: "https://lh3.googleusercontent.com/iIzDn013HQ8NR_KZhaXGeLld6jaszvmRbdrKMGoYuB5MZOZI7ZM6V58yVFHqIuOuJGALhKcKn8vwXTBLf-csPpwaHE5f7YEFIj_KS2SVMcVbQlc=w1600-rj-l80-nu-e365",
        interestId: [15, 3, 4],
        rate: 10,
    },
]
