name: Generate ER Diagram

on:
    push:
        branches:
            - DB

jobs:
    genER:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Read Schema
              id: schema
              uses: juliangruber/read-file-action@v1
              with:
                  path: ./backend/prisma/schema.prisma

            - name: Check schema
              run: echo "${{ steps.schema.outputs.content }}"
            - name: Make request
              id: request
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "https://prisma-erd.simonknott.de/api/render-dml-to-mermaid"
                  method: "POST"
                  customHeaders: '{"Content-Type": "text/plain"}'
                  data: "${{ steps.package.outputs.content }}"
            - name: Get Er
              run: echo ${{ steps.myRequest.outputs.response }}
